version: '3.9'
services:
  package-dev:
    container_name: package-dev
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
          PORT: $PORT
    volumes:
      - ../:/app
      - /app/node_modules
    ports:
      - "$PORT:$PORT"
    stdin_open: true
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
